name: 'Buildx Action'
description: 'Build images using dockerx'
runs:
  using: "composite"
  steps:
    - run: echo ${{ github.action_path }}/buildkit.toml
      shell: bash
    - run: docker buildx create --use --name tevel --append --config=${{ github.action_path }}/buildkit.toml --driver-opt network=host --buildkitd-flags --oci-worker-net=host
      shell: bash
    - run: docker buildx inspect --bootstrap
      shell: bash
