name: 'Buildx Action'
description: 'Build images using dockerx'
runs:
  using: "composite"
  steps:
    - run: docker buildx create --use --node tevel --name tevel --config=${{ github.action_path }}/buildkit.toml
      shell: bash
    - run: docker buildx inspect --bootstrap
      shell: bash
